Vagrant.configure("2") do |config|
  config.vm.define "ubuntu2404" do |ubuntu2404|
    ubuntu2404.vm.box = "bento/ubuntu-24.04"
    ubuntu2404.vm.box_version = "202404.26.0"
    ubuntu2404.vm.network "private_network", ip: "172.16.44.180"

    ubuntu2404.vm.provision "file", source: "./vagrant-box-files/hello-world.service", destination: "/tmp/hello-world.service"

    ubuntu2404.vm.provision "shell",
      inline: <<-INLINE_SCRIPT
        mv /tmp/hello-world.service /etc/systemd/system/hello-world.service
        systemctl enable hello-world
        systemctl start hello-world
        INLINE_SCRIPT
  end

  config.vm.define "fedora40" do |fedora40|
    fedora40.vm.box = "bento/fedora-40"
    fedora40.vm.box_version = "202404.23.0"
    fedora40.vm.network "private_network", ip: "172.16.44.181"

    fedora40.vm.provision "file", source: "./vagrant-box-files/hello-world.service", destination: "/tmp/hello-world.service"

    fedora40.vm.provision "shell",
      inline: <<-INLINE_SCRIPT
        mv /tmp/hello-world.service /etc/systemd/system/hello-world.service
        systemctl enable hello-world
        systemctl start hello-world
        INLINE_SCRIPT
  end
end
