package git

type Commit struct {
	Hash                           string `json:"Hash"`
	AbbreviatedHash                string `json:"AbbreviatedHash"`
	TreeHash                       string `json:"TreeHash"`
	AbbreviatedTreeHash            string `json:"AbbreviatedTreeHash"`
	ParentHashes                   string `json:"ParentHashes"`
	AbbreviatedTree                string `json:"AbbreviatedTree"`
	AuthorName                     string `json:"AuthorName"`
	AuthorNameMailmap              string `json:"AuthorNameMailmap"`
	AuthorEmail                    string `json:"AuthorEmail"`
	AuthorEmailMailmap             string `json:"AuthorEmailMailmap"`
	AuthorEmailLocalPart           string `json:"AuthorEmailLocalPart"`
	AuthorEmailLocalPartMailmap    string `json:"AuthorEmailLocalPartMailmap"`
	AuthorDate                     string `json:"AuthorDate"`
	AuthorDateRFC2822              string `json:"AuthorDateRFC2822"`
	AuthorDateUNIX                 string `json:"AuthorDateUNIX"`
	AuthorDateISO8601Like          string `json:"AuthorDateISO8601Like"`
	AuthorDateISO8601Strict        string `json:"AuthorDateISO8601Strict"`
	AuthorDateShort                string `json:"AuthorDateShort"`
	CommitterName                  string `json:"CommitterName"`
	CommitterNameMailmap           string `json:"CommitterNameMailmap"`
	CommitterEmail                 string `json:"CommitterEmail"`
	CommitterEmailMailmap          string `json:"CommitterEmailMailmap"`
	CommitterEmailLocalPart        string `json:"CommitterEmailLocalPart"`
	CommitterEmailLocalPartMailmap string `json:"CommitterEmailLocalPartMailmap"`
	CommitterDate                  string `json:"CommitterDate"`
	CommitterDateRFC2822           string `json:"CommitterDateRFC2822"`
	CommitterDateUNIX              string `json:"CommitterDateUNIX"`
	CommitterDateISO8601Like       string `json:"CommitterDateISO8601Like"`
	CommitterDateISO8601Strict     string `json:"CommitterDateISO8601Strict"`
	CommitterDateShort             string `json:"CommitterDateShort"`
	RefNames                       string `json:"RefNames"`
	RefNamesUnwrapped              string `json:"RefNamesUnwrapped"`
	Encoding                       string `json:"Encoding"`
	Subject                        string `json:"Subject"`
	SubjectSanitised               string `json:"SubjectSanitised"`
	Body                           string `json:"Body"`
	CommitNotes                    string `json:"CommitNotes"`
	VerificationMessageRaw         string `json:"VerificationMessageRaw"`
	SignerName                     string `json:"SignerName"`
	SigningKey                     string `json:"SigningKey"`
	SigningKeyFingerprint          string `json:"SigningKeyFingerprint"`
	SigningKeyTrustLevel           string `json:"SigningKeyTrustLevel"`
	ReflogSelector                 string `json:"ReflogSelector"`
	ReflogSelectorShortened        string `json:"ReflogSelectorShortened"`
	ReflogIdentityName             string `json:"ReflogIdentityName"`
	ReflogIdentityNameMailmap      string `json:"ReflogIdentityNameMailmap"`
	ReflogIdentityEmail            string `json:"ReflogIdentityEmail"`
	ReflogIdentityEmailMailmap     string `json:"ReflogIdentityEmailMailmap"`
	ReflogSubject                  string `json:"ReflogSubject"`
}
